-- Data Cleanup
CALL SYSTEM.AFL_WRAPPER_ERASER ('AFL_PAL_MISSING_VALUES_PROC');
DROP TYPE ML_MV.PAL_MISSING_VALUES_DATA_T;
DROP TYPE ML_MV.PAL_CONTROL_T;
DROP TYPE ML_MV.PAL_MISSING_VALUES_RESULT_T;
DROP TYPE ML_MV.PAL_MISSING_VALUES_NULL_MAP_T;

DROP TABLE "ML_MV"."PAL_MISSING_VALUES_DATA_TBL";
DROP TABLE "ML_MV"."PAL_MISSING_VALUES_NULL_MAP_TBL";
DROP TABLE "ML_MV"."PAL_MISSING_VALUES_PDATA_TBL";
DROP TABLE "ML_MV"."PAL_MISSING_VALUES_RESULT_TBL";
DROP SCHEMA "ML_MV";
-- Data Cleanup ------------------------------------

-- PAL Setup
CREATE SCHEMA ML_MV;
SET SCHEMA ML_MV;
    --- Source Table 
CREATE TYPE ML_MV.PAL_MISSING_VALUES_DATA_T AS TABLE(
	"V0" INTEGER,
	"V1" DOUBLE, 
	"V2" VARCHAR(5)
);
    --- Parameter Table type
CREATE TYPE ML_MV.PAL_CONTROL_T AS TABLE(
	"NAME" VARCHAR(100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
    --- Result Table type
CREATE TYPE ML_MV.PAL_MISSING_VALUES_RESULT_T AS TABLE(
	"V0" INTEGER,
	"V1" DOUBLE, 
	"V2" VARCHAR(5)
);
	--- Mapping value table
CREATE TYPE ML_MV.PAL_MISSING_VALUES_NULL_MAP_T AS TABLE(
	"ATTRIBUTE_NAME" VARCHAR(20),
	"ATTRIBUTE_VALUE" VARCHAR(20),
	"HIT_TIMES" INTEGER
);

    --- Insert Data to the Predictive model
CREATE COLUMN TABLE "ML_MV"."PAL_MISSING_VALUES_PDATA_TBL" (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO "ML_MV"."PAL_MISSING_VALUES_PDATA_TBL" VALUES (1, 'ML_MV.PAL_MISSING_VALUES_DATA_T', 'IN'); 
INSERT INTO "ML_MV"."PAL_MISSING_VALUES_PDATA_TBL" VALUES (2, 'ML_MV.PAL_CONTROL_T', 'IN'); 
INSERT INTO "ML_MV"."PAL_MISSING_VALUES_PDATA_TBL" VALUES (3, 'ML_MV.PAL_MISSING_VALUES_RESULT_T', 'OUT'); 
INSERT INTO "ML_MV"."PAL_MISSING_VALUES_PDATA_TBL" VALUES (4, 'ML_MV.PAL_MISSING_VALUES_NULL_MAP_T', 'OUT');	

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('AFL_PAL_MISSING_VALUES_PROC', 'AFLPAL', 'SUBSTITUTE_MISSING_VALUES',"ML_MV"."PAL_MISSING_VALUES_PDATA_TBL");
-- PAL Setup -------------------


-- App setup
CREATE COLUMN TABLE "ML_MV".PAL_MISSING_VALUES_DATA_TBL LIKE PAL_MISSING_VALUES_DATA_T;
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (1 , 0.5, 'A');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (1 , 1.5, 'A');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (2 , 1.5, 'A');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (3 , 0.5, 'A');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (4 , 1.1, 'A');

INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (5 , 0.5, 'B');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (6 , 1.5, 'B');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (7 , 1.5, 'B');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (8 , null, 'B');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (null , 1.2, null);

INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (10, 15.5, 'C');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (11, 16.5, 'C');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (12, 16.5, 'C');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (13, 15.5, 'C');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (null, 15.6, 'D'); 

INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (15, 15.5, null);
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (16, 16.5, 'D');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (17, 16.5, 'D');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (18, 15.5, 'D');
INSERT INTO "ML_MV".PAL_MISSING_VALUES_DATA_TBL VALUES (19, 15.7, 'A'); 
 
DROP TABLE "ML_MV".#PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE "ML_MV"."#PAL_CONTROL_TBL" (
	"NAME" VARCHAR(100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO "ML_MV"."#PAL_CONTROL_TBL" VALUES ('V0', 100, null, null);
INSERT INTO "ML_MV"."#PAL_CONTROL_TBL" VALUES ('V1', 201, null, null);
INSERT INTO "ML_MV"."#PAL_CONTROL_TBL" VALUES ('V2', 100, null, null);
-- App setup-----------------------------------

-- App Runtime
CREATE COLUMN TABLE "ML_MV"."PAL_MISSING_VALUES_RESULT_TBL" LIKE "ML_MV"."PAL_MISSING_VALUES_RESULT_T";
CREATE COLUMN TABLE "ML_MV"."PAL_MISSING_VALUES_NULL_MAP_TBL" LIKE "ML_MV"."PAL_MISSING_VALUES_NULL_MAP_T";

CALL _SYS_AFL.AFL_PAL_MISSING_VALUES_PROC(
    "ML_MV"."PAL_MISSING_VALUES_DATA_TBL", 
    "ML_MV"."#PAL_CONTROL_TBL", 
    "ML_MV"."PAL_MISSING_VALUES_RESULT_TBL", 
    "ML_MV"."PAL_MISSING_VALUES_NULL_MAP_TBL") with OVERVIEW;

SELECT * FROM "ML_MV"."PAL_MISSING_VALUES_RESULT_TBL";
SELECT * FROM "ML_MV"."PAL_MISSING_VALUES_NULL_MAP_TBL";
-- App Runtime------------------------------
