

DROP TYPE "DM_PAL".PAL_PCA_DATA_T;
DROP TYPE "DM_PAL".PAL_CONTROL_T;
DROP TYPE "DM_PAL".PAL_PCA_LOADINGS_T;
DROP TYPE "DM_PAL".PAL_PCA_LOADINGS_INFO_T;
DROP TYPE "DM_PAL".PAL_PCA_SCORES_T;
DROP TYPE "DM_PAL".PAL_PCA_SCALING_INFO_T;

DROP TABLE "DM_PAL".PAL_PCA_PDATA_TBL;
DROP TABLE "DM_PAL"."#PAL_CONTROL_TBL";
DROP TABLE "DM_PAL".PAL_PCA_DATA_TBL;
DROP TABLE "DM_PAL".PAL_PCA_LOADINGS_TBL;
DROP TABLE "DM_PAL".PAL_PCA_LOADINGS_INFO_TBL;
DROP TABLE "DM_PAL".PAL_PCA_SCORES_TBL;
DROP TABLE "DM_PAL".PAL_PCA_SCALING_INFO_TBL;

DROP SCHEMA "DM_PAL";
-- PAL Setup
CREATE SCHEMA "DM_PAL";
SET SCHEMA "DM_PAL";
CREATE TYPE "DM_PAL".PAL_PCA_DATA_T AS TABLE("ID" INTEGER, "X1" DOUBLE, "X2" DOUBLE, "X3" DOUBLE, "X4" DOUBLE, "X5" DOUBLE, "X6" DOUBLE);
CREATE TYPE "DM_PAL".PAL_CONTROL_T AS TABLE("NAME" VARCHAR(50), "INTARGS" INTEGER, "DOUBLEARGS" DOUBLE, "STRINGARGS" VARCHAR(100));
CREATE TYPE "DM_PAL".PAL_PCA_LOADINGS_T AS TABLE("PCID" VARCHAR(50), "X1_WEIGHT" DOUBLE, "X2_WEIGHT" DOUBLE, "X3_WEIGHT" DOUBLE, "X4_WEIGHT" DOUBLE, "X5_WEIGHT" DOUBLE, "X6_WEIGHT" DOUBLE);
CREATE TYPE "DM_PAL".PAL_PCA_LOADINGS_INFO_T AS TABLE("PCID" VARCHAR(50),"SDEV" DOUBLE, "PROPORTION" DOUBLE, "CUM_PROPORTION" DOUBLE);
CREATE TYPE "DM_PAL".PAL_PCA_SCORES_T AS TABLE("ID" INTEGER, "Comp1" DOUBLE, "Comp2" DOUBLE, "Comp3" DOUBLE, "Comp4" DOUBLE, "Comp5" DOUBLE, "Comp6" DOUBLE);
CREATE TYPE "DM_PAL".PAL_PCA_SCALING_INFO_T AS TABLE("ID" INTEGER, "MEAN_VECTOR" DOUBLE, "SCALE_VECTOR" DOUBLE);

CREATE COLUMN TABLE "DM_PAL".PAL_PCA_PDATA_TBL("POSITION" INT, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));

INSERT INTO "DM_PAL".PAL_PCA_PDATA_TBL VALUES(1, 'DM_PAL', 'PAL_PCA_DATA_T', 'IN');
INSERT INTO "DM_PAL".PAL_PCA_PDATA_TBL VALUES(2, 'DM_PAL', 'PAL_CONTROL_T', 'IN');
INSERT INTO "DM_PAL".PAL_PCA_PDATA_TBL VALUES(3, 'DM_PAL', 'PAL_PCA_LOADINGS_T', 'OUT');
INSERT INTO "DM_PAL".PAL_PCA_PDATA_TBL VALUES(4, 'DM_PAL', 'PAL_PCA_LOADINGS_INFO_T', 'OUT');
INSERT INTO "DM_PAL".PAL_PCA_PDATA_TBL VALUES(5, 'DM_PAL', 'PAL_PCA_SCORES_T', 'OUT');
INSERT INTO "DM_PAL".PAL_PCA_PDATA_TBL VALUES(6, 'DM_PAL', 'PAL_PCA_SCALING_INFO_T', 'OUT');

CALL SYS.AFLLANG_WRAPPER_PROCEDURE_DROP('DM_PAL','PAL_PCA_PROC');

CALL SYS.AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL','PCA','DM_PAL','PAL_PCA_PROC',"DM_PAL".PAL_PCA_PDATA_TBL);
-- PAL Setup -----------------------

--App Setup + APP Runtime
CREATE COLUMN TABLE "DM_PAL".PAL_PCA_DATA_TBL LIKE "DM_PAL".PAL_PCA_DATA_T;
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (1, 12, 52, 20, 44, 48, 16);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (2, 12, 57, 25, 45, 50, 16);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (3, 12, 54, 21, 45, 50, 16);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (4, 13, 52, 21, 46, 51, 17);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (5, 14, 54, 24, 46, 51, 17);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (6, 22, 52, 25, 54, 58, 26);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (7, 22, 56, 26, 55, 58, 27);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (8, 17, 52, 21, 45, 52, 17);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (9, 15, 53, 24, 45, 53, 18);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (10, 23, 54, 23, 53, 57, 24);
INSERT INTO "DM_PAL".PAL_PCA_DATA_TBL VALUES (11, 25, 54, 23, 55, 58, 25);

CREATE LOCAL TEMPORARY COLUMN TABLE "DM_PAL"."#PAL_CONTROL_TBL" (
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100));
INSERT INTO "DM_PAL"."#PAL_CONTROL_TBL" VALUES ('SCALING', 1, NULL, NULL);
INSERT INTO "DM_PAL"."#PAL_CONTROL_TBL" VALUES ('SCORES', 1, NULL, NULL);

CREATE COLUMN TABLE "DM_PAL".PAL_PCA_LOADINGS_TBL LIKE "DM_PAL".PAL_PCA_LOADINGS_T;
CREATE COLUMN TABLE "DM_PAL".PAL_PCA_LOADINGS_INFO_TBL LIKE "DM_PAL".PAL_PCA_LOADINGS_INFO_T;
CREATE COLUMN TABLE "DM_PAL".PAL_PCA_SCORES_TBL LIKE "DM_PAL".PAL_PCA_SCORES_T;
CREATE COLUMN TABLE  "DM_PAL".PAL_PCA_SCALING_INFO_TBL LIKE "DM_PAL".PAL_PCA_SCALING_INFO_T;

CALL DM_PAL.PAL_PCA_PROC("DM_PAL".PAL_PCA_DATA_TBL,"DM_PAL"."#PAL_CONTROL_TBL", "DM_PAL".PAL_PCA_LOADINGS_TBL, 
"DM_PAL".PAL_PCA_LOADINGS_INFO_TBL, "DM_PAL".PAL_PCA_SCORES_TBL, "DM_PAL".PAL_PCA_SCALING_INFO_TBL) WITH OVERVIEW;

--App Setup + APP Runtime-------------------------------

SELECT * FROM "DM_PAL".PAL_PCA_LOADINGS_TBL;
SELECT * FROM "DM_PAL".PAL_PCA_LOADINGS_INFO_TBL;
SELECT * FROM "DM_PAL".PAL_PCA_SCORES_TBL;
SELECT * FROM "DM_PAL".PAL_PCA_SCALING_INFO_TBL;
