-- Data Cleanup
DROP TYPE PAL_PARTITION_DATA_T;
DROP TYPE PAL_CONTROL_T;   
DROP TYPE PAL_PARTITION_OUT_T;
DROP table PAL_PARTITION_PDATA_TBL;
DROP TABLE PAL_PARTITION_DATA_TBL;
DROP TABLE #PAL_CONTROL_TBL;
DROP TABLE PAL_PARTITION_OUT_TBL;
call SYS.AFLLANG_WRAPPER_PROCEDURE_DROP('DM_PAL','PAL_PARTITION_PROC');
DROP SCHEMA DM_PAL;
-- Data Cleanup ------------------------------------

-- PAL Setup
CREATE SCHEMA DM_PAL;
SET SCHEMA DM_PAL;

CREATE TYPE PAL_PARTITION_DATA_T AS TABLE(
 "ID" INTEGER,
    "HomeOwner" VARCHAR (100), 
    "MaritalStatus" VARCHAR (100),
    "AnnualIncome" DOUBLE,
    "DefaultedBorrower" VARCHAR (100)
);

CREATE TYPE PAL_CONTROL_T AS TABLE( 
    "NAME" VARCHAR (100),
 "INTARGS" INTEGER,
 "DOUBLEARGS" DOUBLE,
 "STRINGARGS" VARCHAR (100)
);

CREATE TYPE PAL_PARTITION_OUT_T AS TABLE(
 "ID" INTEGER,
    "TYPE" INTEGER
);

CREATE column table PAL_PARTITION_PDATA_TBL("POSITION" INT,"SCHEMA_NAME" NVARCHAR(256),"TYPE_NAME" NVARCHAR (256),"PARAMETER_TYPE" VARCHAR (7));
insert into PAL_PARTITION_PDATA_TBL values (1,'DM_PAL','PAL_PARTITION_DATA_T','IN'); 
insert into PAL_PARTITION_PDATA_TBL values (2,'DM_PAL','PAL_CONTROL_T','IN'); 
insert into PAL_PARTITION_PDATA_TBL values (3,'DM_PAL','PAL_PARTITION_OUT_T','OUT'); 

call SYS.AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL','PARTITION','DM_PAL','PAL_PARTITION_PROC',PAL_PARTITION_PDATA_TBL);
-- PAL Setup -------------------

-- App Setup + Runtime
CREATE COLUMN TABLE PAL_PARTITION_DATA_TBL LIKE PAL_PARTITION_DATA_T;
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (0, 'YES','Single',125,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (1, 'NO','Married',100,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (2, 'NO','Single',70,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (3, 'YES','Married',120,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (4, 'NO','Divorced',95,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (5, 'NO','Married',60,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (6, 'YES','Divorced',220,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (7, 'NO','Single',85,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (8, 'NO','Married',75,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (9, 'NO','Single',90,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (10, 'YES','Single',125,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (11, 'NO','Married',100,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (12, 'NO','Single',70,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (13, 'YES','Married',120,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (14, 'NO','Divorced',95,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (15, 'NO','Married',60,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (16, 'YES','Divorced',220,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (17, 'NO','Single',85,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (18, 'NO','Married',75,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (19, 'NO','Single',90,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (20, 'YES','Single',125,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (21, 'NO','Married',100,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (22, 'NO','Single',70,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (23, 'YES','Married',120,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (24, 'NO','Divorced',95,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (25, 'NO','Married',60,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (26, 'YES','Divorced',220,'NO');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (27, 'NO','Single',85,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (28, 'NO','Married',75,'YES');
INSERT INTO PAL_PARTITION_DATA_TBL VALUES (29, 'NO','Single',90,'YES');


CREATE LOCAL TEMPORARY TABLE #PAL_CONTROL_TBL LIKE PAL_CONTROL_T;
INSERT INTO #PAL_CONTROL_TBL VALUES ('PARTITION_METHOD',0,null,null); 
INSERT INTO #PAL_CONTROL_TBL VALUES ('RANDOM_SEED',23,null,null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('TRAINING_PERCENT', null,0.6,null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('TESTING_PERCENT', null,0.2,null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('VALIDATION_PERCENT', null,0.2,null);


CREATE COLUMN TABLE PAL_PARTITION_OUT_TBL LIKE PAL_PARTITION_OUT_T;
CALL DM_PAL.PAL_PARTITION_PROC(PAL_PARTITION_DATA_TBL, "#PAL_CONTROL_TBL", PAL_PARTITION_OUT_TBL) with overview;
-- App Setup + Runtime-----------------------


select * from PAL_PARTITION_OUT_TBL;
