-- Data Cleanup

DROP TYPE DM_PAL.PAL_VT_DATA_T;
DROP TYPE DM_PAL.PAL_VT_RESULT_T;
DROP TYPE DM_PAL.PAL_VT_TEST_T;
DROP TYPE DM_PAL.PAL_VT_CONTROL_T;
DROP table DM_PAL.PAL_VT_PDATA_TBL;
DROP TABLE DM_PAL.PAL_VT_DATA_TBL;
DROP TABLE DM_PAL.PAL_VT_RESULT_TBL;
DROP TABLE DM_PAL.PAL_VT_TEST_TBL;
CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_DROP('DM_PAL', 'PAL_VARIANCE_TEST_PROC');
DROP SCHEMA DM_PAL;
-- Data Cleanup ------------------------------------

-- PAL Setup
CREATE SCHEMA DM_PAL;
SET SCHEMA DM_PAL;
CREATE TYPE PAL_VT_DATA_T AS TABLE (
	"ID" INTEGER,
	"X" DOUBLE
);
CREATE TYPE PAL_VT_RESULT_T AS TABLE(
	"MEAN" DOUBLE,
	"SD" DOUBLE
);
CREATE TYPE PAL_VT_TEST_T AS TABLE(
	"ID" INTEGER,
	"Test" INTEGER
);
CREATE TYPE PAL_VT_CONTROL_T AS TABLE(
	"NAME" VARCHAR(100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
CREATE COLUMN TABLE PAL_VT_PDATA_TBL(
	"POSITION" INT,
	"SCHEMA_NAME" NVARCHAR(256),
	"TYPE_NAME" NVARCHAR(256),
	"PARAMETER_TYPE" VARCHAR(7)
);
INSERT INTO PAL_VT_PDATA_TBL VALUES (1, 'DM_PAL', 'PAL_VT_DATA_T', 'IN'); 
INSERT INTO PAL_VT_PDATA_TBL VALUES (2, 'DM_PAL', 'PAL_VT_CONTROL_T', 'IN'); 
INSERT INTO PAL_VT_PDATA_TBL VALUES (3, 'DM_PAL', 'PAL_VT_RESULT_T', 'OUT'); 
INSERT INTO PAL_VT_PDATA_TBL VALUES (4, 'DM_PAL', 'PAL_VT_TEST_T', 'OUT');


CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'VARIANCETEST', 'DM_PAL', 'PAL_VARIANCE_TEST_PROC', PAL_VT_PDATA_TBL);
-- PAL Setup ------------------------------------

-- App setup + App Runtime
DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL (
	"NAME" VARCHAR(100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('SIGMA_NUM', null, 4.0, null);
-- INSERT INTO #PAL_CONTROL_TBL VALUES ('SIGMA_NUM', null, 5.0, null);


CREATE COLUMN TABLE PAL_VT_DATA_TBL LIKE PAL_VT_DATA_T;
INSERT INTO PAL_VT_DATA_TBL VALUES (0,25);
INSERT INTO PAL_VT_DATA_TBL VALUES (1,20);
INSERT INTO PAL_VT_DATA_TBL VALUES (2,23);
INSERT INTO PAL_VT_DATA_TBL VALUES (3,29);
INSERT INTO PAL_VT_DATA_TBL VALUES (4,26);
INSERT INTO PAL_VT_DATA_TBL VALUES (5,23);
INSERT INTO PAL_VT_DATA_TBL VALUES (6,22);
INSERT INTO PAL_VT_DATA_TBL VALUES (7,21);
INSERT INTO PAL_VT_DATA_TBL VALUES (8,22);
INSERT INTO PAL_VT_DATA_TBL VALUES (9,25);
INSERT INTO PAL_VT_DATA_TBL VALUES (10,26);
INSERT INTO PAL_VT_DATA_TBL VALUES (11,28);
INSERT INTO PAL_VT_DATA_TBL VALUES (12,29);
INSERT INTO PAL_VT_DATA_TBL VALUES (13,27);
INSERT INTO PAL_VT_DATA_TBL VALUES (14,26);
INSERT INTO PAL_VT_DATA_TBL VALUES (15,23);
INSERT INTO PAL_VT_DATA_TBL VALUES (16,22);
INSERT INTO PAL_VT_DATA_TBL VALUES (17,23);
INSERT INTO PAL_VT_DATA_TBL VALUES (18,25);
INSERT INTO PAL_VT_DATA_TBL VALUES (19,103);

CREATE COLUMN TABLE PAL_VT_RESULT_TBL LIKE PAL_VT_RESULT_T;
CREATE COLUMN TABLE PAL_VT_TEST_TBL LIKE PAL_VT_TEST_T;
CALL "DM_PAL".PAL_VARIANCE_TEST_PROC(PAL_VT_DATA_TBL, "#PAL_CONTROL_TBL", PAL_VT_RESULT_TBL, PAL_VT_TEST_TBL) with overview;
-- App setup + App Runtime------------------------------


SELECT * FROM PAL_VT_RESULT_TBL;
SELECT * FROM PAL_VT_TEST_TBL;
