-- Cleanup 
DROP TYPE ML_ABC.PAL_T_ABC_DATA;
DROP TYPE ML_ABC.PAL_T_ABC_PARAMS;
DROP TYPE ML_ABC.PAL_T_ABC_RESULTS;
DROP TABLE ML_ABC.PAL_ABC_SIGNATURE;
DROP VIEW ML_ABC."V_ABC_DATA";
DROP TABLE "ML_ABC"."ABC_PARAMS";
DROP TABLE "ML_ABC"."ABC_RESULTS";
CALL SYSTEM.AFL_WRAPPER_ERASER ('ML_ABC_PAL_ABC'); -- Delete the WRAPPER PROCEDURE

-- PAL Setup
SET SCHEMA ML_ABC;
CREATE TYPE ML_ABC.PAL_T_ABC_DATA AS TABLE (CUSTOMER VARCHAR(60), LIFESPEND DOUBLE);
CREATE TYPE ML_ABC.PAL_T_ABC_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE ML_ABC.PAL_T_ABC_RESULTS AS TABLE (ABC VARCHAR(60), CUSTOMER VARCHAR(60));

CREATE COLUMN TABLE ML_ABC.PAL_ABC_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO ML_ABC.PAL_ABC_SIGNATURE VALUES (1, 'ML_ABC.PAL_T_ABC_DATA', 'in');
INSERT INTO ML_ABC.PAL_ABC_SIGNATURE VALUES (2, 'ML_ABC.PAL_T_ABC_PARAMS', 'in');
INSERT INTO ML_ABC.PAL_ABC_SIGNATURE VALUES (3, 'ML_ABC.PAL_T_ABC_RESULTS', 'out');

CALL SYSTEM.AFL_WRAPPER_GENERATOR ('ML_ABC_PAL_ABC', 'AFLPAL', 'ABC', ML_ABC.PAL_ABC_SIGNATURE);

-- App setup

CREATE VIEW ML_ABC.V_ABC_DATA AS 
	SELECT CUSTOMER, LIFESPEND
		FROM "ML_ABC"."PAL_SQL.PAL_ABC::abc.CUSTOMERS"
	;
CREATE COLUMN TABLE ML_ABC.ABC_PARAMS LIKE ML_ABC.PAL_T_ABC_PARAMS;
CREATE COLUMN TABLE ML_ABC.ABC_RESULTS LIKE ML_ABC.PAL_T_ABC_RESULTS;

INSERT INTO ML_ABC.ABC_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO ML_ABC.ABC_PARAMS VALUES ('PERCENT_A', null, 0.1, null);
INSERT INTO ML_ABC.ABC_PARAMS VALUES ('PERCENT_B', null, 0.2, null);
INSERT INTO ML_ABC.ABC_PARAMS VALUES ('PERCENT_C', null, 0.7, null);

-- App runtime
UPDATE ML_ABC.ABC_PARAMS SET DOUBLEARGS=0.05 WHERE NAME='PERCENT_A';
UPDATE ML_ABC.ABC_PARAMS SET DOUBLEARGS=0.15 WHERE NAME='PERCENT_B';
UPDATE ML_ABC.ABC_PARAMS SET DOUBLEARGS=0.8 WHERE NAME='PERCENT_C';

TRUNCATE TABLE ML_ABC.ABC_RESULTS;

CALL _SYS_AFL.ML_ABC_PAL_ABC ("ML_ABC"."V_ABC_DATA", "ML_ABC"."ABC_PARAMS", "ML_ABC"."ABC_RESULTS") WITH OVERVIEW;
