-- Cleanup
DROP TABLE "ML_APRIORI"."AP_PARAMS";
DROP TABLE "ML_APRIORI"."AP_PMML";
DROP TABLE "ML_APRIORI"."AP_RULES";
DROP TABLE "ML_APRIORI"."PAL_AP_SIGNATURE";
DROP VIEW "ML_APRIORI"."V_AP_DATA";
DROP VIEW "ML_APRIORI"."V_AP_RULES";
DROP TYPE "ML_APRIORI"."PAL_AP_T_DATA";
DROP TYPE "ML_APRIORI"."PAL_AP_T_PARAMS";
DROP TYPE "ML_APRIORI"."PAL_AP_T_PMML";
DROP TYPE "ML_APRIORI"."PAL_AP_T_RULES";


--PAL Setup
SET SCHEMA ML_APRIORI;
CREATE TYPE ML_APRIORI.PAL_AP_T_DATA AS TABLE ("ORDERID" INT, "PRODUCTID" INT);
CREATE TYPE ML_APRIORI.PAL_AP_T_PARAMS AS TABLE (NAME VARCHAR(60), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR (100));
CREATE TYPE ML_APRIORI.PAL_AP_T_RULES AS TABLE ("PRERULE" VARCHAR(500), "POSTRULE" VARCHAR(500), 
"SUPPORT" DOUBLE, "CONFIDENCE" DOUBLE, "LIFT" DOUBLE);
CREATE TYPE ML_APRIORI.PAL_AP_T_PMML AS TABLE ("ID" INT, "PMMLMODEL" VARCHAR(5000));

CREATE COLUMN TABLE ML_APRIORI.PAL_AP_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO ML_APRIORI.PAL_AP_SIGNATURE VALUES (1, 'ML_APRIORI.PAL_AP_T_DATA', 'in');
INSERT INTO ML_APRIORI.PAL_AP_SIGNATURE VALUES (2, 'ML_APRIORI.PAL_AP_T_PARAMS', 'in');
INSERT INTO ML_APRIORI.PAL_AP_SIGNATURE VALUES (3, 'ML_APRIORI.PAL_AP_T_RULES', 'out');
INSERT INTO ML_APRIORI.PAL_AP_SIGNATURE VALUES (4, 'ML_APRIORI.PAL_AP_T_PMML', 'out');
CALL SYSTEM.AFL_WRAPPER_ERASER ('ML_APRIORI_APRIORI');
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('ML_APRIORI_APRIORI', 'AFLPAL', 'APRIORIRULE', ML_APRIORI.PAL_AP_SIGNATURE);

-- APP setup
CREATE VIEW ML_APRIORI.V_AP_DATA AS 
	SELECT "ORDERID", "PRODUCTID" 
		FROM "ML_APRIORI"."PAL_SQL::apriori.FCTCUSTOMERORDER"
		ORDER BY "ORDERID", "PRODUCTID"
	;
CREATE COLUMN TABLE ML_APRIORI.AP_PARAMS LIKE ML_APRIORI.PAL_AP_T_PARAMS;
CREATE COLUMN TABLE ML_APRIORI.AP_RULES LIKE ML_APRIORI.PAL_AP_T_RULES;
CREATE COLUMN TABLE ML_APRIORI.AP_PMML LIKE ML_APRIORI.PAL_AP_T_PMML;


INSERT INTO ML_APRIORI.AP_PARAMS VALUES ('MIN_SUPPORT', null, 0.001, null);
INSERT INTO ML_APRIORI.AP_PARAMS VALUES ('MIN_CONFIDENCE', null, 0.001, null);
INSERT INTO ML_APRIORI.AP_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO ML_APRIORI.AP_PARAMS VALUES ('MAX_ITEM_LENGTH', 10, null, null);
INSERT INTO ML_APRIORI.AP_PARAMS VALUES ('PMML_EXPORT', 0, null, null);
INSERT INTO ML_APRIORI.AP_PARAMS VALUES ('OPTIMIZATION_TYPE', 0, null, null);
INSERT INTO ML_APRIORI.AP_PARAMS VALUES ('IS_RECALCULATE', 0, null, null);

--App runtime
CALL _SYS_AFL.ML_APRIORI_APRIORI (ML_APRIORI.V_AP_DATA, 
ML_APRIORI.AP_PARAMS, 
ML_APRIORI.AP_RULES, 
ML_APRIORI.AP_PMML) WITH OVERVIEW;

--Let's Now refine the model:

UPDATE ML_APRIORI.AP_PARAMS SET DOUBLEARGS=0.001 WHERE NAME='MIN_SUPPORT';
UPDATE ML_APRIORI.AP_PARAMS SET DOUBLEARGS=0.2 WHERE NAME='MIN_CONFIDENCE';
UPDATE AP_PARAMS SET INTARGS=2 WHERE NAME='PMML_EXPORT';
TRUNCATE TABLE ML_APRIORI.AP_RULES;
TRUNCATE TABLE ML_APRIORI.AP_PMML;


CALL _SYS_AFL.ML_APRIORI_APRIORI (ML_APRIORI.V_AP_DATA, 
ML_APRIORI.AP_PARAMS, 
ML_APRIORI.AP_RULES, 
ML_APRIORI.AP_PMML) WITH OVERVIEW;


-- Refine the Rule data with the below view:
CREATE VIEW ML_APRIORI.V_AP_RULES AS
 SELECT "PRERULE" || ' => ' || "POSTRULE" AS "RULE", 
		ROUND("SUPPORT", 4) AS "SUPPORT", 
		ROUND("CONFIDENCE", 4) AS "CONFIDENCE", 
		ROUND("LIFT", 4) AS "LIFT"
  FROM ML_APRIORI.AP_RULES
 ;

